### ISSUE TITLE
Is there still a Non-OOP version?

### ISSUE THREAD

**Issue by f0o** [alanszlosek/dbFacile#10]
Hi,

essentially the title says it :)

**Comment by alanszlosek** [comment]
If you go back in the git history you can find it. I don't remember how stable it was, so good luck :-)

https://github.com/alanszlosek/dbFacile/commit/529e25527238d1a11a1a46252d8be423f00af9bb

**Comment by f0o** [comment]
fair enough thanks! :+1:
