### ISSUE TITLE
Avoid escaping during update

### ISSUE THREAD

**Issue by mbutomax** [alanszlosek/dbFacile#4]
In the README.txt file in the C. Insert/update Data section is said that we can avoid escaping a field by wrapping it in an array.
But there is nothing in the code of the class that do the "dirty work" of ignoring the escape.
I have this need because I want to use this library and want to pass a NULL value to a particular field (obtaining something like this:
update TABLE set FIELDNAME=NULL

In the function makeQuery (line 218) there is nothing that take in consideration the wrapping.

So I made some little changes. If you want to take them in consideration... here they are.
Original (row 232):
			$query .= "'" . $this->escapeString( array_shift($parameters) ) . "'";

Substituted with:
			$current = array_shift($parameters);
			if ( is_array($current) ) {
				$query .= $current[0];
			} else {
				$query .= "'" . $this->escapeString( $current ) . "'";
			}

Hope this helps.
Cheers!

**Comment by polesapart** [comment]
Should this issue be closed by now?

**Comment by alanszlosek** [comment]
Recently added the \dbFacile\passthrough class to support this functionality.

`$set_data = array('visits' => 134, 'last_seen' => new \dbFacile\passthrough('now()'));`
`$db->update('users', $set_data, 'name=', 'Aiden');`
